export const ACTION_SUCCESS = 'ACTION_SUCCESS'
export const ACTION_FAILURE = 'ACTION_FAILURE'
export const ACTION_WAIT = 'ACTION_WAIT'
export const ACTION_RESET = 'ACTION_RESET'

export const SET_SERVERS = 'SET_SERVERS'
export const SET_SERVER = 'SET_SERVER'
export const DEL_SERVER = 'DEL_SERVER'
export const REQUEST_SERVER = 'REQUEST_SERVER'
export const REQUEST_SERVER_SUCCESS = 'REQUEST_SERVER_SUCCESS'
export const REQUEST_SERVER_RESET = 'REQUEST_SERVER_RESET'

export const SET_VOLUMES = 'SET_VOLUMES'
export const SET_VOLUME = 'SET_VOLUME'

export const SET_TYPES = 'SET_TYPES'
export const SET_TYPE = 'SET_TYPE'

export const SET_IMAGES = 'SET_IMAGES'
export const SET_IMAGE = 'SET_IMAGE'

export const SET_FLAVORS = 'SET_FLAVORS'
export const SET_FLAVOR = 'SET_FLAVOR'

export const SET_NETWORKS = 'SET_NETWORKS'
export const SET_NETWORK = 'SET_NETWORK'
